### ISSUE TITLE
Fatal Error Autoloader nach Installation

### ISSUE THREAD

**Issue by hirnsturm** [lochmueller/focuspoint#1]
Nach der Installation unter TYPO3 CMS 6.2.13 kommt es zu folgendem Fehler:
```
Detected Fatal Error
Class 'HDNET\Autoloader\Loader' not found in /var/www/typo3_629/typo3conf/ext/focuspoint/ext_localconf.php on line 7
```
Fehlen hier eventuell Abhängigkeiten in der *ext_emconf.php*?

**Comment by lochmueller** [comment]
Hallo... die Abhänigkeiten sind eingetragen (siehe: http://typo3.org/extensions/repository/view/focuspoint und https://github.com/lochmueller/focuspoint/blob/master/ext_emconf.php ). Wenn du jedoch eine Extension aus dem TER heruter geladen hast und manuell im BE von TYPO3 wieder hoch, dann fehlen die dependencies. Das ist ein Fehler vom TER Frontend. Es ist zu empfehlen die Extensions immer über das Backend zu installieren... nur dann passen die Abhänigkeiten. Alterantiv: Manuell prüfen. Vorweg bitte die "autoloader" Extension installieren.

Ich schließe das Ticket direkt. Wenn das nicht das Problem ist, bitte ein neues aufmachen. Zudem bitte auf Englisch, sodass alle aus der Community von der Frage/Antwort/Hilfe profitieren können....

**Comment by hirnsturm** [comment]
Hat geklappt. Vielen Dank. 

Seltsam ist es trotzdem, dass wenn ich die Extension (Version 1.2.1) aus dem TER herunterlade und installiere, keine Abhängigkeiten geladen werden. Zudem standen auch in der *ext_emconf.php* keine drin.

**Comment by lochmueller** [comment]
Jup... komisch ist es. Ist aber ein Fehler vom TER. :(
