### ISSUE TITLE
Percentage values

### ISSUE THREAD

**Issue by mcmz** [lochmueller/focuspoint#10]
Would it be possible to have direct access to the percentage values in the near future? 

In a way that you can easily use it for pure CSS with TS, so that no focuspoint frontend plugin is needed, just the backend module? like …

```javascript
page.cssInline { 
    ...
    renderObj = IMG_RESOURCE
    ...
    0.postCObject.value = background-position: left {fp:wp} bottom {fp:yp};
```

Many thanks in advance
Martin

**Comment by lochmueller** [comment]
Hey @mcmz 

is this enough?? https://github.com/lochmueller/focuspoint/commit/b6096944c990a7db2470c31320766f291c0c9301
This only works if the current file is in the right context...

Regards,
Tim

**Comment by mcmz** [comment]
Hi Tim, 
thanks for the direct response. Its nearly there, except that the "background-position" property needs positive percentage values, as the CSS grid is ment to be seen from the left / upper corner initially.
http://www.w3.org/TR/css3-background/#background-position

The **FocusPoint Helper Tool** explains this behavior perfectly:
http://jonom.github.io/jquery-focuspoint/demos/helper/index.html

Thank you very much and best regards 
Martin

**Comment by lochmueller** [comment]
I Add a positive version of the value. If this is not the right value, please create a pull request with the classification number that you need...

Regards,
Tim
