### ISSUE TITLE
Many error messages in the TYPO3 log from focuspoint

### ISSUE THREAD

**Issue by alsodenn** [lochmueller/focuspoint#110]
We have noticed that we have quite a few error messages from focuspoint in the log of TYPO3. These error messages don't mean anything to me, but probably to you? I don't notice any misbehaviour from the extension because of this error message, but maybe there are other problems because of it? Thanks for taking a look and fixing it.

TYPO3: 12.4.10
Focuspoint: 6.0.4 

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Unsupported operand types: string * int | TypeError thrown in file /vendor/lochmueller/focuspoint/Classes/Controller/BackendController.php in line 47. Requested URL: https://domain.ch/typo3/wizard/focuspoint?token=--AnonymizedToken--&save=1&P%5BreturnUrl%5D=/typo3/record/edit?token%3D--AnonymizedToken--%26edit%255Btt_content%255D%255B4173%255D%3Dedit%26returnUrl%3D/typo3/module/web/layout?token%253Db68af1dc9b1c604bb8a4d933c830f8b563eb1748%2526id%253D1831%2523element-tt_content-4173&P%5BreferenceUid%5D=9655&yValue=&xValue=`

**Comment by lochmueller** [comment]
Hey @alsodenn ,
fixed in version 6.0.5.
Regards,
Tim
