### ISSUE TITLE
TYPO3 13

### ISSUE THREAD

**Issue by paulAtSlim** [lochmueller/focuspoint#112]
Is it possible to make it available for TYPO3 13? :)
TY

**Comment by lochmueller** [comment]
Hey @paulAtSlim ,
yes it is possible, but currently not without financial or dev support.
Feel free to start the migration and send PR.
Regards,
Tim

**Comment by lochmueller** [comment]
I close this issue. Feel free to send PR for compatible versions for TYPO3 v13.

**Comment by alsodenn** [comment]
Hi @lochmueller 
We would like to sponsor the version for TYPO3 13 LTS again. 
Can you make me an offer? You should still have my contact details ;-).

**Comment by lochmueller** [comment]
Hey @paulAtSlim 
Hey @alsodenn 

version 7.0.0 was released a few minutes ago.

Regards,
Tim
