### ISSUE TITLE
ImageViewHelper is not returning div class="focuspoint" 

### ISSUE THREAD

**Issue by tm-webentwicklung** [lochmueller/focuspoint#113]
Since version 6.0.0 we find this code in ImageViewHelper.php:

try {
    return $this->originalRender();
} catch (\Exception $ex) {
    return 'Missing image!';
}

This leads to "return" in both cases and ending the function here. So all the rest of function "render", e.g. generating $focusTag, will never be executed. Which breaks the plugin completely. Am I missing something or has this never been working under TYPO3 version 12?

**Comment by lochmueller** [comment]
Only the "real crop" is supported in newer versions. The originalRender handle the call of the parent in the right way. The code below this method is not for TYPO3 v12 and can be removed (or someone enable the JS crop solutation again).

**Comment by lochmueller** [comment]
Codes was removed for the next version
