### ISSUE TITLE
Responsive Header IMG with pure CSS

### ISSUE THREAD

**Issue by mcmz** [lochmueller/focuspoint#12]
Hi Tim,

according to the newly submitted pull request i want to share the correponding TS. The header files are integrated inwards the **page relations** in **three different sizes**. Additional CSS for the image container has been set to:
```css
.bgimg {
    width: 100%;
    height: 600px;
    display: block;
}
```

The Integration is done by TS inlineCSS like so:

```typoscript

page.cssInline {

	// needed to let dataWrap 
	// recognize curly brackets
	1 = LOAD_REGISTER
	1.curl1 = {
	1.curl2 = }

	// <source>
	10 = FILES
	10 {

		// get the reference from pages > media
		references {
			table = pages
			uid.data = page:uid
			fieldName = media
		}

		renderObj = IMG_RESOURCE
		renderObj {

	  		// import file
			file.import.data = file:current:uid
			file.treatIdAsReference = 1

	      stdWrap.dataWrap.cObject = CASE
	      stdWrap.dataWrap.cObject {

	      	// get files by sorting num
	      	key.data = register:FILE_NUM_CURRENT

	      	// sm
	      	0 = TEXT
	      	0.value = background-image: url(|); 
	      	0.postCObject = TEXT	
	      	0.postCObject.value = background-position: left {fp:xp_positive}% top {fp:yp_positive}%;
	      	0.postCObject.if.isTrue.data = fp:xp
	      	0.wrap = .bgimg {register:curl1} | {register:curl2}

	      	// md
	      	1 < .0
	      	1.outerWrap = @media only screen and (min-width: 600px) {register:curl1} | {register:curl2} 

	      	// lg
	        2 < .0
	      	2.outerWrap = @media only screen and (min-width:1024px) {register:curl1} | {register:curl2} 

	      }
	      stdWrap.wrap = /|

	  }
	  
		begin = 0
		maxItems = 3

		stdWrap.outerWrap ( 
			/* background-image with focus point*/ 
				|
			/* */ 
		)

	}

}

```

**Comment by lochmueller** [comment]
Hey @mcmz 

Is it OK if I use that snippet in the documentation of the extension as example?

Regards,
Tim

**Comment by mcmz** [comment]
Yes, for sure. 
Best regards 
Martin

**Comment by lochmueller** [comment]
Great... I started the documentation with you example. Thank you.

**Comment by mcmz** [comment]
Hey Tim,

please be so kind and support the TS snippet by mentioning my name und 
site:
martin zarth – www.zarthwork.de

Danke und frohe Weihnachten
Martin


Tim schrieb:
>
> Great... I started the documentation with you example. Thank you.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/lochmueller/focuspoint/issues/12#issuecomment-166160444>.
>

-- 
martin zarth visuelle & digitale kommunikation  
vogelsanger straße 286 50825 Köln
martin@zarthwork.de http://www.zarthwork.de

**Comment by lochmueller** [comment]
Done: https://github.com/lochmueller/focuspoint/commit/032fa097f6ad1e3e05f423c6dc17cb1a917e5a5a
