### ISSUE TITLE
Focuspoint Extension hat in TYPO3 7.6.2 Probleme mit .tiff Bildformaten

### ISSUE THREAD

**Issue by mansoorahmadhh** [lochmueller/focuspoint#14]
Hallo Tim,

anbei im anhang.zip die Testdatei von dem Dateiformat tiff, sowie die Fehlerscreens. In dem ersten Screenshot taucht die Vorschau der Tiffdatei nicht auf, während in dem zweiten Screenshot man sieht, das die TYPO3 Preview Function die Tiff Bildformate rendert. Getestet wurde das mit dem TYPO3 Default Image Element.

Hoffe das hilft weiter.

[anhang.zip](https://github.com/lochmueller/focuspoint/files/117243/anhang.zip)

**Comment by lochmueller** [comment]
Hey @mansoorahmadhh 
I prepare the right function: https://github.com/lochmueller/focuspoint/commit/25c48f8c6348fe52a46fc30db135a2786cef3905
In this function all formats have to be converted to PNG/JPEG that are no displayable in the browser.
Regards,
Tim

**Comment by mansoorahmadhh** [comment]
We can here use this Previewimage Function for all formats like

typo3/sysext/filelist/Classes/FileList.php

$processedFile = $fileObject->process(ProcessedFile::CONTEXT_IMAGEPREVIEW, array());
$processedFile->getPublicUrl(true);
