### ISSUE TITLE
Bug während des AJAX-Nachladens von Elementen

### ISSUE THREAD

**Issue by timwehrmann** [lochmueller/focuspoint#15]
Hallo Tim,

ich bin über einen komischen Fehler im List- sowie im Page-Modul gestolpert: Wenn ich in einem bestehenden News-Datensatz unter Content Elements mehrere normale "Text & Media" ergänzt habe und nachträglich im entsprechenden News-Datensatz nun bei einem Bild einen Focuspunkt setzen will, schlägt dies mit der Alert-Meldung "Please save the base record first, because open this wizard will not save the changes in the current form!" fehl.

Ich habe mich an der Stelle ein wenig in den Code eingegraben und _(äußerst wahrscheinlich)_ die Ursache gefunden: Wenn per AJAX ein Datensatz im List Modul nachgeladen wird, scheitert es in der _focuspoint/Classes/Hooks/InlineRecord.php_ in Zeile 95 beim if mit _isset($arguments['edit'])_:

Das $arguments-Array sieht bei einem AJAX Request im List Modul so aus:

```
Array (
    [ajaxID] => /ajax/record/inline/details
    [ajaxToken] => d8d0bcdb46bc31dc835a75dbfac5885b8ea037aa
)
```

Wird das Element direkt beim Seitenaufruf geladen, kommt dieses Beispiel-Array bei rum:

```
Array (
    [route] => /record/edit
    [token] => b3b7289b1c6d50dd6ccd76f6cb510ebd93563277
    [edit] => Array
        (
            [tt_content] => Array
                ( [30613] => edit )
        )
    [returnUrl] => /typo3/index.php?M=web_list&moduleToken=9f51c861ab652ac088768e92f1fc29654165aa92&id=2043&
    [L] => 0
)
```

Beispielhafte und reproduzierbare Anwendungsfälle im Listenmodul:
- Listmodul: In einem Newsdatensatz mit mehreren zugeklappten "Text & Media"-Elementen in der "Content Elements"-Section
- List-/Page-Modul: In einem GridElement mit mehreren zugeklappten "Text & Media"-Elementen sowie mit eigenen angelegten Contentelementen, bei denen Bilder gepflegt werden können

Hier ist eine Bildschirmaufnahme des Bugs _(bei dem per AJAX nachgeladenen Elementen schlägt es fehl, bei den mit Elementaufruf geladenen Elementen klappt es)_: https://youtu.be/ehHhirYt1vQ

**Comment by lochmueller** [comment]
Hallo @xBlubbs

Danke für das Melden des Fehlers (demnächst besser in Englisch, weil dann die ganze Community mitreden kann). Der Fehler ist bekannt, ich habe aber noch keine gute Lösung finden können. Ich werde mir dies in den nächsten Tagen/Wochen nochmals mit anschauen...

Grüße,
Tim

**Comment by xBlubbs** [comment]
Roger that! :)

**Comment by jagodzinski** [comment]
Hallo,

gibt es hierzu mittlerweile einen Fix?

Viele Grüße,
Jessica

**Comment by lochmueller** [comment]
Hey @jagodzinski 
no. There are no news on this topic.
Regards,
Tim

**Comment by lochmueller** [comment]
Hey @timwehrmann,
I found no good solution for this problem, because the core hook do not provide the current data, so the information are based on the request params directly. And I saw no other solution. I will close this issue here.
Regards,
Tim
