### ISSUE TITLE
Make compatible with TYPO3 8.x

### ISSUE THREAD

**Issue by sascha-egerer** [lochmueller/focuspoint#18]
The extension is marked as compatible with TYPO3 8.1 but it is not as it uses a function (`\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addModulePath()`) that was deprecated in TYPO3 7 and is removed in 8.

**Comment by lochmueller** [comment]
Thanks for the bugreport. Please take a look at the current master. I migrate the code...
