### ISSUE TITLE
"Check for broken extensions" fails

### ISSUE THREAD

**Issue by sneopu** [lochmueller/focuspoint#23]
The function "Check for broken extensions" fails in the install tool with Focuspoint v2.0.0.

Pressing the Button leads to endless recursion of the call. Which fails with a server error 500.

`PHP Fatal error:  Call to a member function exec_SELECTgetRows() on null in /here_the_path_to webdirectory/web/typo3conf/ext/focuspoint/Configuration/TCA/Overrides/tt_content.php on line 20, referer: http://start.frontalprojects.ch/typo3/sysext/install/Start/Install.php?install[redirectCount]=4&install[context]=backend&install[controller]=tool
`

Could you reproduce this issue?

TYPO3 7.6.11
focuspoint 2.0.0
autoloader 2.1.5

**Comment by lochmueller** [comment]
Thanks for the report. Fixed in the current master. I moved the DB related stuff to a itemsProcFunc function, so the DB is not selected in the TCA generation anymore...
