### ISSUE TITLE
Extension manager: focuspoint description is broken

### ISSUE THREAD

**Issue by cweiske** [lochmueller/focuspoint#24]
The "description" of focuspoint 2.1.2 in the TYPO3 extension manager is only

> w and directly in the content element.

**Comment by lochmueller** [comment]
Hey @cweiske 
this seems to be a problem of the core. The description is "TYPO3 conform" and complete in the extension: https://github.com/lochmueller/focuspoint/blob/master/ext_emconf.php#L15

I close this issue...

Regards,
Tim

**Comment by lochmueller** [comment]
PS: Here is also the complete description: https://typo3.org/extensions/repository/view/focuspoint
Sounds like ExtensionManager issue...
