### ISSUE TITLE
SQL error after save image

### ISSUE THREAD

**Issue by dkd-faerber** [lochmueller/focuspoint#28]
Hey, i've installed the extension via composer. After setting a focus point and saving, nothing happens. When i set the coordinates in image settings it gets me this error: 
2: SQL error: 'Unknown column 'focus_point_y' in 'field list'' (sys_file_metadata:84)

How does the additional fields from your extension are added without an ext_tables.sql? What am i doing wrong? Please help :)

I'm using TYPO3 7.6.10.

Best regards, Anna

**Comment by lochmueller** [comment]
Hey @dkd-faerber 
is EXT:autoloader also successfully installed? If both extensions (autoloader, focuspoint) are installed, please clear the caches and run the DB compare in the install tool...

The fields are added by the model annotations, via the EXT:autoloader extension. So it is right, that there is no ext_tables.sql...

Regards,
Tim

**Comment by dkd-faerber** [comment]
Hey, thanks for the fast answer. Just thought that autoloader is already in because of all the other extensions. But it appears that its an extra extension form your side. So that helps. Thank you.

Regards Anna
