### ISSUE TITLE
Extension won't create DB-fields 

### ISSUE THREAD

**Issue by shugden** [lochmueller/focuspoint#3]
I installed the Extension on Typo3 6.2.9 after that i have to add the database fields "focouspoint_x, focuspoint_y, ratio" manually.

**Comment by lochmueller** [comment]
Hey shugden,

please check the installation process and/or run database compare. The extension create fields via the TYPO3 autoloader extension.

Can you check this again?

Regards,
Tim

**Comment by lochmueller** [comment]
No feeedback...
