### ISSUE TITLE
Wrong link generation in backend for save button in FocusPoint Backend Module 

### ISSUE THREAD

**Issue by juergen-venne** [lochmueller/focuspoint#30]
Not sure if this is a FP issue:
I create a new News, assign a media image, save the news, click the FP icon aside of the image. The save icon has a wrong link:
`http://xxxxxxx.de/typo3/index.php?route=%2Fwizard%2Ffocuspoint&token=7ab061e02975c9a8ba8532bcb94198a66c42cac6&save=1&P%5BreturnUrl%5D=%2Ftypo3%2Findex.php%3Froute%3D%252Frecord%252Fedit%26token%3D38a31529480c16516d28d8fe9361232ab0ef8d48%26edit%255Btx_news_domain_model_news%255D%255B2%255D%3Dnew%26returnUrl%3D%252Ftypo3%252Findex.php%253FM%253Dweb_list%2526moduleToken%253Dd762007c74250f23f5d2e74f075a55e613cfbb2e%2526id%253D2%2526imagemode%253D1&P%5BreferenceUid%5D=11284`
After clicking save a new news is created instead of returning to the current news.
Slightly changeing the workflow genarates the correct link:
Create a new News, **save the news**,  assign a media image, click the FP icon aside of the image:
`
http://xxxxxxx.de/typo3/index.php?route=%2Fwizard%2Ffocuspoint&token=7ab061e02975c9a8ba8532bcb94198a66c42cac6&save=1&P%5BreturnUrl%5D=%2Ftypo3%2Findex.php%3Froute%3D%252Frecord%252Fedit%26token%3D38a31529480c16516d28d8fe9361232ab0ef8d48%26edit%255Btx_news_domain_model_news%255D%255B29184%255D%3Dedit%26returnUrl%3D%252Ftypo3%252Findex.php%253FM%253Dweb_list%2526moduleToken%253Dd762007c74250f23f5d2e74f075a55e613cfbb2e%2526id%253D2%2526imagemode%253D1&P%5BreferenceUid%5D=11283
`

**Comment by lochmueller** [comment]
This is a FP issue, but I do not habe a smart solution ;) The record has to be exists (incl. UID) before FP can handle the coodinates on the record...

**Comment by lijunfan** [comment]
Thank you. I'll teach my editors to do that the working way.
