### ISSUE TITLE
Inline JS, initial call

### ISSUE THREAD

**Issue by dkd-faerber** [lochmueller/focuspoint#31]
Hey Tim, 
I think this line
` jsFooterInline.1001.value = $(document).ready(function(){ $('.focuspoint').focusPoint(); });
` have to be modified to: 
`jsFooterInline.1001.value = $(document).ready(function(){if($('.focuspoint').length) {
				$('.focuspoint').focusPoint();
			} });
` ?
Because otherwise it runs in error on pages without .focuspoint images. What do you think?

**Comment by lochmueller** [comment]
Hey Anna,
thanks for the note... will be part  of the next release.
Regards,
Tim
