### ISSUE TITLE
Follow semver

### ISSUE THREAD

**Issue by mbrodala** [lochmueller/focuspoint#34]
I noticed that the versioning of this extension does not follow [semver](http://semver.org/), the latest release (2.1.4) states that it drops support for TYPO3 6.2. In semver this would mean that the version should've been 3.0.0 instead.

Please consider switching to semver to support reliable and predictable updates.

**Comment by lochmueller** [comment]
Sorry... I noticed the 6.2 drop after I push the release. I will pay attention next time.... sorry!

**Comment by mbrodala** [comment]
Thanks. :-)
