### ISSUE TITLE
Typoscript rendering GIFBUILDER inside GIFBUILDER does not work

### ISSUE THREAD

**Issue by hirnschmalz** [lochmueller/focuspoint#38]
The following TypoScript code will cause an uncaught Exception like

**PHP Warning: imagecreatefrompng(/typo3temp/GB/dsv1_7d529b1517.png): failed to open stream: No such file or directory in /path/to/webroot/TYPO3.CMS/typo3/sysext/core/Classes/Imaging/GraphicalFunctions.php line 2952**

```typoscript
myImage = IMG_RESOURCE
myImage .file = GIFBUILDER
myImage .file {
	XY = [10.w],[10.h]
	format = jpg
	quality = 80

	10 = IMAGE
	10.file = GIFBUILDER
	10.file {
		XY = [10.w],[10.h]
		format = png

		10 = IMAGE
		10.file = EXT:references/Resources/Private/Images/iMac.png
	}
}
```

The problem seems to be the wrong path given to `imagecreatefrompng` (the path to the webroot is missing as far as I can see).

PHP: 7
TYPO3 CMS: 7.6.16
OS: Ubuntu 16.06.2 LTS

**Comment by lochmueller** [comment]
Won't fix anymore. Thanks for reporting, but GIFBUILDER is not in the focus of the extension.
