### ISSUE TITLE
error when cs_seo is installed

### ISSUE THREAD

**Issue by mithri** [lochmueller/focuspoint#39]
BE error when focuspoint and cs_seo 2.0.0 are installed:

Argument 2 passed to HDNET\Focuspoint\Hooks\GetData::getDataExtension() must be of the type array, null given, called in /kunden/308915_57627/pap/11855/34/typo3cms/huf_2016/typo3_src-7.6.15/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php on line 6069

with cs_seo 1.8.x it worked.

**Comment by mithri** [comment]
The same with the solr extension.

**Comment by lochmueller** [comment]
Hey @mithri 
It is no problem of focuspoint i think. The Interface \TYPO3\CMS\Frontend\ContentObject\ContentObjectGetDataHookInterface - that is used by the hook - required a "array" as second param. So I cannot change this behavior.
Regards,
Tim

**Comment by mithri** [comment]
Ah sorry. Yes i saw that yesterday, too. Weird thing is that in one setup it works, and in another not. I couldn`t find the root problem of this so far.

Please close this bug report.

Thanks.
Tobias
