### ISSUE TITLE
filelist cache problem

### ISSUE THREAD

**Issue by keyrider** [lochmueller/focuspoint#41]
typo3 7.6.16
focuspoint 2.1.4

There seems to be a cache problem when replacing an image. If a focuspoint was set afore, focuspoint wizard will keep loading the "old" image instead of loading the new (replaced) image. In frontend everythings works fine. However, setting the focuspoint without seeing the image your are "focussing" is quite unhandy...

The dynamic reference system within typo3 gains its power, as you can replace / rename / etc any file, as you like without necessarily touching referencing content elements afterwards.

That bug makes this powerful features of typo3 absurd.

**Comment by lochmueller** [comment]
Hmm... do you use TIFF/TIF? Could you hard reload the page and check if it is a browser caching bug or if the file is not the new one? Please send me some more information (please check the Service/Handler).
Regards,
Tim

**Comment by lochmueller** [comment]
Close this issue (no feedback)
