### ISSUE TITLE
works not on Bootstrap_Package on Typo3 8.7.4

### ISSUE THREAD

**Issue by alexd0001** [lochmueller/focuspoint#49]
Hi,
Focuspoint works not on Bootstrap_Package on Typo3 8.7.4 - It is possible make this Extension compatible with bootstrap_package?

**Comment by lochmueller** [comment]
@alexd0001 Do you have some more information? "works not" is a very general bug description ;) Do you get some errors? Missing functions? Exceptions?

**Comment by alexd0001** [comment]
Hi, yes. It seems to work an all instances, but in FE it takes no effekt in ratio on the images. 

I put a Image in a Image-Content-Element which have a defined Focuspoint of your Extension. I can use a ratio provided by your Extension in the property. 

It seems all to be ok, but it does not work.

**Comment by lochmueller** [comment]
You have to overwrite the viewHelper of the Fluid Rendering:
https://github.com/benjaminkott/bootstrap_package/blob/master/Resources/Private/Partials/ContentElements/Media/Rendering/Image.html
If the Fluid template use the regular ViewHelper FP do not work.

I will close this issue...
