### ISSUE TITLE
Make Focuspoint-Crop available via TypoScript (fe. height=300f width=500f )

### ISSUE THREAD

**Issue by Gang-Rel** [lochmueller/focuspoint#5]
Focuspoint-Data can already be used in TypoScript like this:
width = 500c
width.stdWrap.dataWrap = |{file:current:focus_point_x}

But there are 2 small issues:
1) y-axis must be inverted, but works like this:
height = 
height.wrap = 300c|
height.stdWrap.dataWrap = |(-1)*{file:current:focus_point_y}
height.prioriCalc = 1

2) The focuspoint doesn't get centered like in the preview. Apparently the TypoScript-standard-crop-move-method differs from the focuspoint-method.

**Comment by lochmueller** [comment]
There is aleady a hook for focuspoint data: https://github.com/lochmueller/focuspoint/commit/cfedc60a756ce98485a435d8cf9bfc97da748965

Should we add same values for the GetData access? Which values are needed....?

**Comment by Gang-Rel** [comment]
Thx that you are looking into this!

Sadly I don't really understand what you say, since I am not a programmer myself but "only" a frontender (can work some Typoscript though).

To elaborate on my issue:
- I would like to use focuspoint-cropping instead of center-cropping universally in regular Typoscript. This is because I use center-cropping a lot and focus-cropping solves problems I regularly encounter with some percentage of images. Especially if the same image is cropped to several different aspect-ratios (f.e. News-Teaser+List+Article)
- I can already use the raw focuspoint x and y values to shift the crop, but that approach is a bit dirty and doesn't give the same result as the preview in fileadmin, which would confuse editors (see first comment).
- I am not really interested in using the js-frontend-cropping-method except for special cases, where I actually want an image to have a flexible aspect-ratio (seldom so far).

I think I remember you have some "real crop"-functionality, which might already do what I want, just in Fluid. For CEs and our own stuff I haven't really moved to Fluid though and I'm not too accustomed to it yet. Might change with 7LTS and the new Standard-Fluid-CEs, obviously.

**Comment by Gang-Rel** [comment]
To maybe actually answer your question:
It would help, if you could calculate the actual values needed to have the regular center-crop shift in the same way as the focuspoint preview, and make those available.

**Comment by lochmueller** [comment]
Realy old ticket... I drop this. FOr TYPO3 CMS 8.x> is the core cropping also a good alterantive.
