### ISSUE TITLE
No focuspoint button for file references

### ISSUE THREAD

**Issue by dkd-lehnebach** [lochmueller/focuspoint#51]
Hi Tim,

i have the issue that the focuspoint button for file references is not being displayed.
Everything else seems to work, like the buttons in Metadata > Categories or in the filelist.

The problem appeared on TYPO3 8.7.3

Best regards
Florian

**Comment by lochmueller** [comment]
Already fixed in the current composer version 2.2.0: https://github.com/lochmueller/focuspoint/commit/bb2c1e748c1284d754a03719d2e8685d3892bcf2
