### ISSUE TITLE
Typo3 8.7.8  Focuspoint 2.2 Error: Argument "src" has already been defined, thus it should not be defined again

### ISSUE THREAD

**Issue by WWFelixMartinez** [lochmueller/focuspoint#53]
Hi, I am getting an error: : Argument "src" has already been defined, thus it should not be defined again.

Typo3 8.7.8
Focuspoint 2.1 and 2.2 (tested both)

It happens with both of the viewhelpers, fp:image and fp:uri.image

**Comment by lochmueller** [comment]
I close this issue. There is already a bug request: https://github.com/lochmueller/fl_realurl_image/issues/21
