### ISSUE TITLE
New icon to fit better into the TYPO3 BE

### ISSUE THREAD

**Issue by sneopu** [lochmueller/focuspoint#54]
It would be nice to have a focuspoint icon, which fits better in the black icon world of the TYPO3 backend.

Something like this:
![23-01-2018 10-50-18](https://user-images.githubusercontent.com/1940935/35269291-de0bc2c0-002b-11e8-9173-bffbdddfbbc6.png)

**Comment by lochmueller** [comment]
Great Idea.... could you create a pull request? Is the icon already part of the TYPO3 icon set or just an example of you?

**Comment by sneopu** [comment]
Okay, I will make a pull request. The proposed icon is just quick example to get a idea, it is not from the TYPO3 icon set. A designer from our company will take care for a nice icon ;-)
Should I only change the backend action icon? Or also the extension icons?
At this time it use the same icon for both cases.

**Comment by lochmueller** [comment]
You could switch both icons... i think.

**Comment by lochmueller** [comment]
Great. The pull request is megerd. WIll be part of the next release...

Regards,
Tim

**Comment by sneopu** [comment]
Thanks that's great. What is your favourite color?

**Comment by lochmueller** [comment]
monochrome black is a good option.

**Comment by sneopu** [comment]
Is there a shedule for the next release in TER?

**Comment by lochmueller** [comment]
I uploaded version 3.0.2 a few seconds ago...

**Comment by sneopu** [comment]
Thanks a lot.

------ Originalnachricht ------
Von: "Tim" <notifications@github.com>
An: "lochmueller/focuspoint" <focuspoint@noreply.github.com>
Cc: "Stephan Brun" <s@brun.tk>; "Author" <author@noreply.github.com>
Gesendet: 05.02.2018 10:49:48
Betreff: Re: [lochmueller/focuspoint] New icon to fit better into the 
TYPO3 BE (#54)
