### ISSUE TITLE
Wizard icon not available in search

### ISSUE THREAD

**Issue by pquerner** [lochmueller/focuspoint#58]
When you search for a image name in the filelist module, the wizard icon is not added in the resultlist. (0 or more results)

TYPO3 7.6.23
(latest avail. versions for 7.x branch of autoloader + focuspoint ext)

**Comment by lochmueller** [comment]
I will check this with the current master and TYPO3 8.x again. There will be no special releases for old TYPO3 versions anymore...

Regards,
Tim

**Comment by lochmueller** [comment]
Hey @pquerner 
The search result page is genrated by fluid (docroot/typo3/sysext/filelist/Resources/Private/Templates/FileList/Search.html) and the hook is not called. So the the right way is, open the item and go to the wizard via the Extended Tab of the Meta data view. There will be no addaptions in focuspoint. Feel free to add a patch if you found a good/smart solution...
Regards,
Tim
