### ISSUE TITLE
PNG24 Tansparent Background is not preserved

### ISSUE THREAD

**Issue by fgerards** [lochmueller/focuspoint#6]
if the source image of the fp:image - ViewHelper is PNG24 with transparent background / alpha layer, this transparancy is NOT preserved when cropping/resizing with the FocusCropService.

Reason is u are not using the GIFBuilder but the underlying GraphicalFunction class directly.
Thus the steps in GIFbuilder to preserve the alpha transparency are NOT executed.

Plz fix.
Thx

**Comment by lochmueller** [comment]
Hey @fgerards 

fixed in current master (version 1.4.0).

Regards,
Tim
