### ISSUE TITLE
Typo3 V9.5 LTS Support

### ISSUE THREAD

**Issue by Schmalztopf** [lochmueller/focuspoint#62]
Hello,
will there be an update for the TYPO3 9.5 LTS Version?
Thanks
Thomas

**Comment by lochmueller** [comment]
Yes... will be release in the next days/weeks...

**Comment by dkoether** [comment]
Hey @lochmueller , are there any updates about a TYPO3 9.5 compatible version of your extension?

**Comment by dkoether** [comment]
Hello @lochmueller , are there any updates about a TYPO3 9.5 compatible version of your extension?

**Comment by lochmueller** [comment]
No. There are no news at the moment... I have to test the extension, before I change the compatibility.

Regards,
Tim

**Comment by lochmueller** [comment]
Current release is compatible with 9.5.
If there are any problems, feel free to create a new issue... 👍
