### ISSUE TITLE
Interface 'TYPO3\CMS\Backend\Form\DatabaseFileIconsHookInterface' not found in Version 3.1.1

### ISSUE THREAD

**Issue by Schmalztopf** [lochmueller/focuspoint#63]
After installing via composer and enabling the extension I get the messeage 
Fatal error: Interface 'TYPO3\CMS\Backend\Form\DatabaseFileIconsHookInterface' not found in /srv/www/vhosts/kigawaldorf/public/typo3conf/ext/focuspoint/Classes/Hooks/GroupItem.php on line 22
in both backend and frontend. 

According to Typo3 changelog, this Interface has been dropped in v9.0 (https://docs.typo3.org/typo3cms/extensions/core/Changelog/9.0/Breaking-80700-DeprecatedFunctionalityRemoved.html)

**Comment by lochmueller** [comment]
Fixed in current master 👍
