### ISSUE TITLE
Errors in Backend and Frontend

### ISSUE THREAD

**Issue by websedit** [lochmueller/focuspoint#64]
Hi
i got the following errors:
Undeclared arguments passed to ViewHelper TYPO3\CMS\Fluid\ViewHelpers\Be\ContainerViewHelper: loadJQuery. Valid arguments are: pageTitle, includeCssFiles, includeJsFiles, addJsInlineLabels, includeRequireJsModules
->Solution: in EXT:focuspoint/Resources/Private/Templates/Wizard/Focuspoint.html Line 3 delete: loadJQuery="0"
to solve this error.

If I do this, the backend seems to work.
But in the frontend there is still this error:
Argument 1 passed to HDNET\Focuspoint\Service\DimensionService::getRatio() must be of the type string, null given, called in /htdocs/typo3conf/ext/focuspoint/Classes/Xclass/LocalCropScaleMaskHelper.php on line 76

I think the problem is here: $currentRecord = $GLOBALS['TSFE']->currentRecord; Line 106
$currentRecord is NULL and this leads to the error.

**Comment by lochmueller** [comment]
Thanks for the information. Both fixed in the current master 👍
