### ISSUE TITLE
Error when using Text&Media and focuspoint extension

### ISSUE THREAD

**Issue by Schmalztopf** [lochmueller/focuspoint#65]
I installed the dev-master of the focuspoint extension and now get the following error:

Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to a member function exec_SELECTgetRows() on null | Error thrown in file /srv/www/vhosts/.../public/typo3conf/ext/focuspoint/Classes/Service/TcaService.php in line 60. Requested URL: http://server/typo3/index.php?route=%%2Frecord%%2Fedit&token=--AnonymizedToken--&edit%%5Btt_content%%5D%%5B10%%5D=new&defVals%%5Btt_content%%5D%%5BcolPos%%5D=0&defVals%%5Btt_content%%5D%%5Bsys_language_uid%%5D=0&returnUrl=%%2Ftypo3%%2Findex.php%%3Froute%%3D%%252Fweb%%252Flayout%%252F%%26token%%3D70d1d0155b2e92187105f99afb83a48806951826%%26id%%3D10&defVals[tt_content][CType]=textmedia&defVals[tt_content][tx_gridelements_columns]=0

Maybe this is an configuration issue. I also get some hints from TCA Migration check, that TCA entries should be updated but I do not know where to do this. 

Best regards
Thomas

**Comment by lochmueller** [comment]
Thanks for the note. I think it was a problem with a TYPO3 9.x installation, right? I migrate all old DB functions to the new ConnectionPool logic. The problem should be gone...

**Comment by Schmalztopf** [comment]
You are right, it was a 9.x installation. Thanks for your effort.

Thomas

Am 03.02.19 um 17:03 schrieb Tim:
