### ISSUE TITLE
getCroppedImageSrcBySrc throws type error if file doesn't exist

### ISSUE THREAD

**Issue by jagodzinski** [lochmueller/focuspoint#66]
Hi,

I get following error when a file isn't available:
TypeError 
Return value of HDNET\Focuspoint\Service\FocusCropService::getCroppedImageSrcBySrc() must be of the type string, null returned

TYPO3 9.5
focuspoint master (d146079496bb76f9a63d3a049aef17673120d3e4)

**Comment by lochmueller** [comment]
Hey @jagodzinski . Thanks for the report. Fixed in current master. Regards. Tim

**Comment by jagodzinski** [comment]
Thank you!
