### ISSUE TITLE
createTempSubDir not found in v9

### ISSUE THREAD

**Issue by mithri** [lochmueller/focuspoint#68]
Hi,

i think this api call was removed in v9.

Oops, an error occurred!
Call to undefined method TYPO3\CMS\Frontend\Imaging\GifBuilder::createTempSubDir()

It is used in the CropService.php at line 163.

Regards,
Tobias

**Comment by lochmueller** [comment]
Hey @mithri ,
thanks for the report: fixed in this commit: https://github.com/lochmueller/focuspoint/commit/e0342ca6d8c595eb0d1f804ac19f6b04e7e82908
I already upload version 3.2.0 a few seconds ago.
Regards,
Tim
