### ISSUE TITLE
abandon use of limited gdlib-image-functions - add TIFF etc. support

### ISSUE THREAD

**Issue by fgerards** [lochmueller/focuspoint#7]
Hi,

this is also related to the PNG-24 issues i posted.
Why dont you use the TYPO3 standard-way for manipulation images via the GIFbuilder-"engine"?  This way, imagemagick will get involved in the correct way. What you do is working on gdlib lib functions, which are very limited when it comes to modern-style graphic manipulation/rendering like PNG-24 and other non-web formats as input

**Comment by lochmueller** [comment]
Hey fgerards,

please post a patch and I will check if everything works. The Non-GIFbuilder way was the quick way. If you think there is a better one, plese contribute same code...

Otherwise I will check the image handling in the next days/weeks...

Regards,
Tim

**Comment by fgerards** [comment]
Hi,
Ok thx 4 info - so there was no special reason to do it without the GIFBuilder?
I will work on a patch to make the service use standard TYPO3 GIFBuilder and thus ensbling TIF/PDF and png-24 handling

**Comment by lochmueller** [comment]
Hey fgerards, no. There was no special reason for not using the GIFBuilder. Thanks for your upcoming contribution...

**Comment by lochmueller** [comment]
Hey @fgerards 

the current version switch to the GifBuilder. Please test your cases with the 1.4.0 release (or master). If there are still problems... please open a new issue (perhaps incl. a patch ;)

Regards,
Tim
