### ISSUE TITLE
Move fluid namespace into config

### ISSUE THREAD

**Issue by kimamil** [lochmueller/focuspoint#72]
Due to https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/8.5/Feature-78415-GlobalFluidViewHelperNamespacesMovedToTYPO3Configuration.html namespaces are not supported inside the templates anymore.

You should be able to add the following line in your ext_localconf.php to have the 'fp' fluid namespace available again in the templates:

$GLOBALS['TYPO3_CONF_VARS']['SYS']['fluid']['namespaces']['fp'][0] = 'HDNET\Focuspoint\ViewHelpers';

**Comment by lochmueller** [comment]
Done. Will be part of the next release...
