### ISSUE TITLE
y-axis centered instead of position

### ISSUE THREAD

**Issue by SimonWpt** [lochmueller/focuspoint#74]
``` 
TYPO3 9.5.14
composer req lochmueller/focuspoint:dev-master
ddev version v1.13.1
``` 

When setting a focal point, the y-axis is centered instead of focal position.

**Backend Setting**
![focal1](https://user-images.githubusercontent.com/160817/77073025-e1d22500-69ee-11ea-84c6-ab96bda1134c.jpg)

**Command**
`<fp:image image="{image}" width="1000c" height="400c" realCrop="true"/>`

**Frontend View**
![focal2](https://user-images.githubusercontent.com/160817/77073018-e1398e80-69ee-11ea-96d5-fed1a96c3312.jpg)

**Comment by SimonWpt** [comment]
Any chance, that this issue will be fixed soon?

**Comment by lochmueller** [comment]
Hey @SimonWpt 
there is no fixed time scheduler for my open source work. Sorry... I try to check this in the next days. Feel free to support me...
Regards,
Tim

**Comment by lochmueller** [comment]
I checked this problem. The reason for this problem are the "c" values for with and height. There is no reason for this, beccause in your layout you know the dimension of the image and you  are using focuspoint to get the right position. Just use regular integer values for height and width and recheck your test szenario.

Thank you.

**Comment by SimonWpt** [comment]
Hello Tim,

thank you for checking my problem. I am a little bit confused, because your examples use the "c" for cropping:

https://github.com/lochmueller/focuspoint#fluid-template-example

Is "c" only available for `realCrop="false"`? 

Thank you again for your effort.

**Comment by lochmueller** [comment]
I think the example is wrong. The usecase of focuspoint is, that you know the dimension and size and focuspoint know the best psoition. The ViewHelper always crop the best position (in realCrop mode) and never crop without real crop (because the FE JS lib do it). So the "c" is not needed.
