### ISSUE TITLE
RuntimeException: Unable to get a property on a non-object

### ISSUE THREAD

**Issue by bihor** [lochmueller/focuspoint#76]
I have this error in my log-file (using TYPO3 9.5.16). Bug of Focuspoint or of Autoloader?

Wed, 13 May 2020 08:59:36 +0000 [ERROR] request="28d0c32fce429" component="TYPO3.CMS.Frontend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Unable to get a property on a non-object. - {"expression":"request.getPageArguments().get('L') < 1","exception":"RuntimeException: Unable to get a property on a non-object. in /web/typo3_src-9.5.16/vendor/symfony/expression-language/Node/GetAttrNode.php:83\nStack trace:\n#0 /web/typo3_src-9.5.16/vendor/symfony/expression-language/Node/BinaryNode.php(90): Symfony\\Component\\ExpressionLanguage\\Node\\GetAttrNode->evaluate(Array, Array)\n#1 /web/typo3_src-9.5.16/vendor/symfony/expression-language/ExpressionLanguage.php(66): Symfony\\Component\\ExpressionLanguage\\Node\\BinaryNode->evaluate(Array, Array)\n#2 /web/typo3_src-9.5.16/typo3/sysext/core/Classes/ExpressionLanguage/Resolver.php(77): Symfony\\Component\\ExpressionLanguage\\ExpressionLanguage->evaluate('request.getPage...', Array)\n#3 /web/typo3_src-9.5.16/typo3/sysext/core/Classes/Configuration/TypoScript/ConditionMatching/AbstractConditionMatcher.php(290): TYPO3\\CMS\\Core\\ExpressionLanguage\\Resolver->evaluate('request.getPage...')\n#4 /web/typo3_src-9.5.16/typo3/sysext/core/Classes/Configuration/TypoScript/ConditionMatching/AbstractConditionMatcher.php(265): TYPO3\\CMS\\Core\\Configuration\\TypoScript\\ConditionMatching\\AbstractConditionMatcher->evaluateExpression('request.getPage...')\n#5 /web/typo3_src-9.5.16/typo3/sysext/core/Classes/TypoScript/Parser/TypoScriptParser.php(296): TYPO3\\CMS\\Core\\Configuration\\TypoScript\\ConditionMatching\\AbstractConditionMatcher->match('[request.getPag...')\n#6 /web/typo3_src-9.5.16/typo3/sysext/core/Classes/TypoScript/TemplateService.php(1220): TYPO3\\CMS\\Core\\TypoScript\\Parser\\TypoScriptParser->parse('\\n[GLOBAL]\\n\\n[GLO...', Object(TYPO3\\CMS\\Frontend\\Configuration\\TypoScript\\ConditionMatching\\ConditionMatcher))\n#7 /web/typo3_src-9.5.16/typo3/sysext/extbase/Classes/Configuration/BackendConfigurationManager.php(73): TYPO3\\CMS\\Core\\TypoScript\\TemplateService->generateConfig()\n#8 /web/typo3_src-9.5.16/typo3/sysext/extbase/Classes/Configuration/AbstractConfigurationManager.php(215): TYPO3\\CMS\\Extbase\\Configuration\\BackendConfigurationManager->getTypoScriptSetup()\n#9 /web/typo3_src-9.5.16/typo3/sysext/extbase/Classes/Configuration/AbstractConfigurationManager.php(151): TYPO3\\CMS\\Extbase\\Configuration\\AbstractConfigurationManager->getExtbaseConfiguration()\n#10 /web/typo3_src-9.5.16/typo3/sysext/extbase/Classes/Configuration/ConfigurationManager.php(127): TYPO3\\CMS\\Extbase\\Configuration\\AbstractConfigurationManager->getConfiguration('focuspoint', NULL)\n#11 /web/typo3_src-9.5.16/typo3/sysext/extbase/Classes/Utility/LocalizationUtility.php(233): TYPO3\\CMS\\Extbase\\Configuration\\ConfigurationManager->getConfiguration('Framework', 'focuspoint')\n#12 /web/typo3_src-9.5.16/typo3/sysext/extbase/Classes/Utility/LocalizationUtility.php(165): TYPO3\\CMS\\Extbase\\Utility\\LocalizationUtility::loadTypoScriptLabels('focuspoint', 'EXT:focuspoint/...')\n#13 /web/typo3_src-9.5.16/typo3/sysext/extbase/Classes/Utility/LocalizationUtility.php(96): TYPO3\\CMS\\Extbase\\Utility\\LocalizationUtility::initializeLocalization('EXT:focuspoint/...', 'default', Array, 'focuspoint')\n#14 /web/typo3conf/ext/autoloader/Classes/Utility/TranslateUtility.php(130): TYPO3\\CMS\\Extbase\\Utility\\LocalizationUtility::translate('plugin.Test', 'focuspoint')\n#15 /web/typo3conf/ext/autoloader/Classes/Utility/TranslateUtility.php(76): HDNET\\Autoloader\\Utility\\TranslateUtility::getLll('plugin.Test', 'focuspoint', NULL)\n#16 /web/typo3conf/ext/autoloader/Classes/Loader/Plugins.php(87): HDNET\\Autoloader\\Utility\\TranslateUtility::getLllOrHelpMessage('plugin.Test', 'focuspoint')\n#17 /web/typo3conf/ext/autoloader/Classes/Loader.php(191): HDNET\\Autoloader\\Loader\\Plugins->loadExtensionTables(Object(HDNET\\Autoloader\\Loader), Array)\n#18 /web/typo3conf/ext/autoloader/Classes/Loader.php(124): HDNET\\Autoloader\\Loader->loadExtTables('HDNET', 'focuspoint', Array)\n#19 /web/typo3temp/var/cache/code/cache_core/ext_tables_860043e56f279ea611bdb38b8e6efb7f42b433f6.php(1106): HDNET\\Autoloader\\Loader::extTables('HDNET', 'focuspoint', Array)\n#20 /web/typo3_src-9.5.16/typo3/sysext/core/Classes/Cache/Backend/SimpleFileBackend.php(366): require('/web/typo3_src-9...')\n#21 /web/typo3_src-9.5.16/typo3/sysext/core/Classes/Cache/Frontend/PhpFrontend.php(122): TYPO3\\CMS\\Core\\Cache\\Backend\\SimpleFileBackend->require('ext_tables_8600...')\n#22 /web/typo3_src-9.5.16/typo3/sysext/core/Classes/Utility/ExtensionManagementUtility.php(1802): TYPO3\\CMS\\Core\\Cache\\Frontend\\PhpFrontend->require('ext_tables_8600...')\n#23 /web/typo3_src-9.5.16/typo3/sysext/core/Classes/Core/Bootstrap.php(867): TYPO3\\CMS\\Core\\Utility\\ExtensionManagementUtility::loadExtTables(true)\n#24 /web/typo3_src-9.5.16/typo3/sysext/backend/Classes/Middleware/BackendRouteInitialization.php(67): TYPO3\\CMS\\Core\\Core\\Bootstrap::loadExtTables()\n#25 /web/typo3_src-9.5.16/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Backend\\Middleware\\BackendRouteInitialization->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#26 /web/typo3_src-9.5.16/typo3/sysext/backend/Classes/Middleware/ForcedHttpsBackendRedirector.php(53): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#27 /web/typo3_src-9.5.16/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Backend\\Middleware\\ForcedHttpsBackendRedirector->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#28 /web/typo3_src-9.5.16/typo3/sysext/backend/Classes/Middleware/LockedBackendGuard.php(71): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#29 /web/typo3_src-9.5.16/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Backend\\Middleware\\LockedBackendGuard->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#30 /web/typo3_src-9.5.16/typo3/sysext/core/Classes/Middleware/NormalizedParamsAttribute.php(58): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#31 /web/typo3_src-9.5.16/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Core\\Middleware\\NormalizedParamsAttribute->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#32 /web/typo3_src-9.5.16/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(67): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#33 /web/typo3_src-9.5.16/typo3/sysext/core/Classes/Http/AbstractApplication.php(108): TYPO3\\CMS\\Core\\Http\\MiddlewareDispatcher->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#34 /web/typo3_src-9.5.16/typo3/sysext/backend/Classes/Http/Application.php(68): TYPO3\\CMS\\Core\\Http\\AbstractApplication->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#35 /web/typo3_src-9.5.16/typo3/sysext/core/Classes/Http/AbstractApplication.php(120): TYPO3\\CMS\\Backend\\Http\\Application->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#36 /web/typo3_src-9.5.16/typo3/index.php(24): TYPO3\\CMS\\Core\\Http\\AbstractApplication->run()\n#37 /web/typo3_src-9.5.16/typo3/index.php(25): {closure}()\n#38 {main}"}

**Comment by lochmueller** [comment]
Hey @bihor 
I don't think it is autoloader or focuspoint. Where the condition "request.getPageArguments().get('L')" comes from?
Regards,
Tim

**Comment by bihor** [comment]
Yes, you are right. I think it is not a problem with focuspoint.
I get similar errors with other expressions too.
