### ISSUE TITLE
No support for php 7.2?

### ISSUE THREAD

**Issue by bmafeldt** [lochmueller/focuspoint#77]
Hi there,

was it intended that there is no support for php 7.2 for any reason? 
The composer.json in branch master says:

`[…] "require": { "php": "^7.3||^7.4", […]`

The ext_emconf.php in the same branch says:

`[…] 'depends' => [ 'php' => '7.2.0-0.0.0',  […]`

I would suggest, that this extension should also support php 7.2, as TYPO3 10 LTS does.

Best regards

**Comment by lochmueller** [comment]
Hey @bmafeldt 
PHP 7.2 is not in active support anymore (only seccurity fixes) and over 2 years old: https://www.php.net/supported-versions.php
I will check this in the future, but it is recommended to upgrade the PHP Version.
Regards,
Ttim

**Comment by lochmueller** [comment]
There will be no new version of focuspoint, for old PHP versinos. I try to release a new release soon.
