### ISSUE TITLE
TCA migrations

### ISSUE THREAD

**Issue by mfellinger-sisi** [lochmueller/focuspoint#84]
Checking TCA migrations in TYPO3 9.5.24 for the 3.2.1 release of focuspoint reports several required TCA migrations:

The slider wizard in TCA sys_file_metadata['columns']['focus_point_y']['config']['wizards']['slider'] has been migrated to sys_file_metadata['columns']['focus_point_y']['config']['slider'].
The slider wizard in TCA sys_file_metadata['columns']['focus_point_x']['config']['wizards']['slider'] has been migrated to sys_file_metadata['columns']['focus_point_x']['config']['slider'].
The slider wizard in TCA sys_file_reference['columns']['focus_point_y']['config']['wizards']['slider'] has been migrated to sys_file_reference['columns']['focus_point_y']['config']['slider'].
The slider wizard in TCA sys_file_reference['columns']['focus_point_x']['config']['wizards']['slider'] has been migrated to sys_file_reference['columns']['focus_point_x']['config']['slider'].
The slider wizard in TCA tx_focuspoint_domain_model_filestandalone['columns']['focus_point_y']['config']['wizards']['slider'] has been migrated to tx_focuspoint_domain_model_filestandalone['columns']['focus_point_y']['config']['slider'].
The slider wizard in TCA tx_focuspoint_domain_model_filestandalone['columns']['focus_point_x']['config']['wizards']['slider'] has been migrated to tx_focuspoint_domain_model_filestandalone['columns']['focus_point_x']['config']['slider'].

When will these be fixed? Should we provide a pulll request?

**Comment by lochmueller** [comment]
Hey @mfellinger-sisi 
thanks for your issue. Feel free to create a pull request with fixes. Please keep in mind, that the current version is 4.0.2 https://github.com/lochmueller/focuspoint/releases/tag/4.0.2 Perhaps there are already changes related to this.
Regards,
Tim
