### ISSUE TITLE
Installation via Composer not possible

### ISSUE THREAD

**Issue by devtroll** [lochmueller/focuspoint#89]
Installation via Composer fails due to the following error message.

`Warning: Undefined array key "image_settings" in /var/www/html/public/typo3conf/ext/focuspoint/Configuration/TCA/Overrides/tt_content.php line 156`

Environment:

- TYPO v11
- PHP 8.1
- DDEV

Can u fix this? Thanks :)

**Comment by lochmueller** [comment]
Hey @devtroll 

Feel free to send a pull request. Error should be fixed after change this:

    if (\is_array($GLOBALS['TCA']['tt_content']['palettes'][$p])) {

To this:

    if (\is_array($GLOBALS['TCA']['tt_content']['palettes'][$p] ?? null)) {

I will check this later...

Regards,
Tim
