### ISSUE TITLE
Make focus point extension available via Composer

### ISSUE THREAD

**Issue by alomvar** [lochmueller/focuspoint#9]
With the release of TYPO3 7.6 LTS and Composer as the new standard way for extension distribution it would be handy to turn this into a Composer package.

**Comment by alomvar** [comment]
Ah sorry, forgot that TER extensions get automatically converted and available [on TYPO3 package repository](https://composer.typo3.org/satis.html#!/focuspoint) (package `typo3-ter/focuspoint`).

**Comment by lochmueller** [comment]
@alomvar 
I add a composer.json for the next release also...
https://github.com/lochmueller/focuspoint/commit/78166c1e0bdacdb0dc980dca9b6d0bec40977f5a
