### ISSUE TITLE
Warning in PHP 8.1

### ISSUE THREAD

**Issue by DaPedro** [lochmueller/focuspoint#93]
Hi together,

when installing the Extension (TYPO3 11 latest + PHP 8.1). The following Warning occurs in Backend: 
```Undefined array key "image_settings" in [...] /ext/focuspoint/Configuration/TCA/Overrides/tt_content.php line 156```

Edit:
The following Line would work:
```if (is_array($GLOBALS['TCA']['tt_content']['palettes'][$p] ?? null)) {```

Best Wishes!

**Comment by lochmueller** [comment]
Hey @DaPedro ,
thanks for direkt closing. As you already found out, the fix is already in the current master: https://github.com/lochmueller/focuspoint/commit/d2f493ca15bd7242a9a63538d8abab1ea75ddff2
Will puch a new version in a few minutes.
Regards,
Tim
