### ISSUE TITLE
Undefined array key warning in wizard

### ISSUE THREAD

**Issue by doleh** [lochmueller/focuspoint#94]
Hi,

similiar to https://github.com/lochmueller/focuspoint/issues/93, following warning occurs when selecting the focuspoint option from file list module:
`PHP Warning: Undefined array key "focus_point_x" in /**...**/ext/focuspoint/Classes/Service/WizardHandler/File.php line 47`

System:
TYPO3 11.5.22
PHP 8.1

**Comment by lochmueller** [comment]
Fixed in current master.
