### ISSUE TITLE
Why are the images saved in the typo3temp directory?

### ISSUE THREAD

**Issue by alsodenn** [lochmueller/focuspoint#95]
TYPO3 Version: 11.5.25
Focuspoint: 5.1.0
Webp: 4.2.0

I wonder why the generated images are stored in the typo3temp directory?

I use the webp extension. However, the images from the typo3temp folder are not taken into account for the conversion to webp.

As a workaround I have now set the extension settings "Directory for generated files" in Focuspoint to a fileadmin folder and also set a filemount to this directory.

Now it seems to work as desired, but it is a bit cumbersome.
Is it possible to set the extension to fileadmin by default, so that it works like other extensions, or is this technically impossible?

**Comment by lochmueller** [comment]
Hey @alsodenn 
this is historically :-/ So we could change this with a configuration, but should still use typo3temp as default, so we don't change the behavior of old systems.
Regards,
Tim
