### ISSUE TITLE
TYPO3 12 LTS

### ISSUE THREAD

**Issue by cundd** [lochmueller/focuspoint#96]
Thank you for creating this helpful extensions.

Is a version for TYPO3 12 LTS already in the making? I can imagine that updating an extension with such a backend-integration is very time consuming.

**Comment by lochmueller** [comment]
Hey @cundd 
No, there is no plan for v12 on my desk. This update is based on Feedback/Pull-Requests or financial support, because I don't use this extension in any v12 project currently by myself.
Regards,
Tim

**Comment by cundd** [comment]
Thank you for your quick feedback. Can you estimate the amount of work it would take?

**Comment by alsodenn** [comment]
Hi @lochmueller 
We would like to support the work for an official TYPO3 12 version.
Can you make us an offer?

**Comment by cundd** [comment]
Great to see you working on this!

**Comment by lochmueller** [comment]
Hey @cundd 
Thanks goes also to @alsodenn who support the development :) The current state is quite good. I think a few tests and the next release will be done in the next days.
Regards,
Tim

**Comment by lochmueller** [comment]
Done. 6.x Release is on Packagist & TER.
Feel free to test and send feedback via issue tracking, if there are problems.

Important: Please disable backend CSP, because the wizard is not working, if the backend sends default CSP.
