### ISSUE TITLE
Check for Broken Extensions shows errors

### ISSUE THREAD

**Issue by lukasnetz** [lochmueller/focuspoint#97]
When i click on Check Extension Compatibility `ext_tables.php` fails to load.

**Comment by lochmueller** [comment]
We have to check this in EXT:autoloader. Thanks for your first cleanups. I dropped TYPO3 v10 and PHP 7.x support: https://github.com/lochmueller/focuspoint/commit/92af718ef9617185e67d34fed36109197655885c and move also the Icon registration to the right place: https://github.com/lochmueller/focuspoint/commit/001939aa437746a175f445d13d1ddab612b367ac

Regards,
Tim

**Comment by lochmueller** [comment]
Done. In Version 6.x EXT:autoloader is not required anymore.
