### ISSUE TITLE
Test Plugin not working

### ISSUE THREAD

**Issue by cundd** [lochmueller/focuspoint#99]
Inserting the test plugin results in the following error on the frontend:

```
TYPO3: v12.4.3
focuspoint: 6.0.1
```

```
[Semantical Error] The annotation "@TYPO3\CMS\Extbase\Annotation\Inject" in property HDNET\Focuspoint\Controller\TestController::$fileRepository was never imported. Did you maybe forget to add a "use" statement for this annotation?
```

**Comment by cundd** [comment]
And more problems coming in.

`TYPO3\CMS\Extbase\SignalSlot\Dispatcher` isn't available anymore in TYPO3 v12 (https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.4/Deprecation-90625-ExtbaseSignalSlotDispatcher.html)

**Comment by cundd** [comment]
But to be honest: I don't care that much about the test plugin.

**Comment by lochmueller** [comment]
Hey @cundd ,
I fixed the SignalSlot problem and introduce two events for this functions. Also switch from Inject to construct DI.
Regards,
Tim
